### ISSUE TITLE
Improving Builder Pattern?

### ISSUE THREAD

**Issue by PedroCarrillo** [maddog05/EasySQLite#1]
Hola, te mencione en un post y queria dejarte a que me refiero. Tal vez no aporte mucho ya que ya utilizas el patron pero creo que como libreria deberias encargarte de la creacion de tus objetos y no permitir que cualquiera haga una nueva instancia de tu objeto a menos que sea necesario. 👍 

```
EasySQLiteColumn() {
        isPK = false;
        isNotNull = false;
        isAutoincremented = false;
}

```

```
public static class Builder {

        public String name;
        public String type;
        public boolean isPK;
        public boolean isNotNull;
        public boolean isAutoincremented;

        public Builder() {
            // Tal vez aqui inicializar lo que inicializas en el constructor de arriba
        }

        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public EasySQLiteColumn build() {
            EasySQLiteColumn easySQLiteColumn = new EasySQLiteColumn();
            easySQLiteColumn.setName(name);
            return easySQLiteColumn;
        }

}


public void Test() {
    EasySQLiteColumn easySQLiteColumn = new EasySQLiteColumn.Builder().name("hola").build();
}
```

Ese seria como anhadir la clase Builder a tu EasySQLiteColumn, y luego lo utilizarias como en el metodo Test. Algo similar puedes ver que usan en Retrofit y Picasso, 
Buen trabajo!
Saludos

**Comment by maddog05** [comment]
Hola @PedroCarrillo Acabo de realizar una actualizacion para optimizar un poco el patron Builder (lo puedes revisar en el README) Continuare para seguir mejorandolo.
Me confirmas si te parece bien el cambio

**Comment by PedroCarrillo** [comment]
Hola, se ve mucho mejor y amigable al usuario. Estaba revisando el codigo y tengo un par de observaciones como:
- La base de datos le haces open y nunca es close, creo que deberia haber una forma de que se cierre ya que si se deja abierto causaria leaks de memoria.
- El helper ayuda a crear las tablas pero de ahi al hacer querys, borrar datos es crear el mismo boilerplate code que antes.

Si tuviera tiempo me gustaria ayudarte pero ahorita no cuento con tiempo :( Igual hazme saber tus opiniones y a ver que solucion tienes :) 👍
